#!/usr/bin/env python3
#
# Copyright 2025 The Krkn Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
KRKN Template CLI Wrapper

This script provides a convenient command-line interface for managing
and running KRKN chaos scenario templates.
"""

import sys
import os

# Add the current directory to Python path to import krkn modules
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from krkn.template_manager import main

if __name__ == "__main__":
    main()
