version: v0.2.0
input:
  root: RootObject
  objects:
    KubernetesTarget:
      id: KubernetesTarget
      properties:
        kubeconfig_path:
          type:
            type_id: string
    RootObject:
      id: RootObject
      properties:
        cpu_hog_enabled:
          type:
            type_id: bool
        pod_chaos_enabled:
          type:
            type_id: bool
        kubeburner_enabled:
          type:
            type_id: bool
        max_parallel_workflows:
          type:
            type_id: integer
            minimum: 1
            default: 3
        workflow_timeout:
          type:
            type_id: integer
            minimum: 60
            default: 3600
        kubernetes_target:
          type:
            type_id: ref
            id: KubernetesTarget
        kubeburner_list:
          type:
            type_id: list
            items:
              type_id: ref
              id: KubeBurner
              namespace: $.steps.kubeburner_wf.execute.inputs.items
        pod_chaos_list:
          type:
            type_id: list
            items:
              type_id: ref
              id: KillPodConfig
              namespace: $.steps.pod_chaos_wf.execute.inputs.items
        cpu_hog_list:
          type:
            type_id: list
            items:
              type_id: ref
              id: CpuHog
              namespace: $.steps.cpu_hog_wf.execute.inputs.items

steps:
  kubeburner_wf:
    kind: foreach
    items: !expr 'bindConstants($.input.kubeburner_list, $.input.kubernetes_target)'
    workflow: subworkflows/kubeburner.yaml
    parallelism: !expr $.input.max_parallel_workflows
    enabled: !expr $.input.kubeburner_enabled
    timeout: !expr $.input.workflow_timeout
    error_handling:
      retry_count: 3
      retry_delay: 30
      continue_on_error: false
  pod_chaos_wf:
    kind: foreach
    items: !expr 'bindConstants($.input.pod_chaos_list, $.input.kubernetes_target)'
    workflow: subworkflows/pod-chaos.yaml
    parallelism: !expr $.input.max_parallel_workflows
    enabled: !expr $.input.pod_chaos_enabled
    timeout: !expr $.input.workflow_timeout
    error_handling:
      retry_count: 3
      retry_delay: 30
      continue_on_error: false
  cpu_hog_wf:
    kind: foreach
    items: !expr 'bindConstants($.input.cpu_hog_list, $.input.kubernetes_target)'
    workflow: subworkflows/cpu-hog.yaml
    parallelism: !expr $.input.max_parallel_workflows
    enabled: !expr $.input.cpu_hog_enabled
    timeout: !expr $.input.workflow_timeout
    error_handling:
      retry_count: 3
      retry_delay: 30
      continue_on_error: false

outputs:
  workflow_success:
    kubeburner: !ordisabled $.steps.kubeburner_wf.outputs.success
    pod_chaos: !ordisabled $.steps.pod_chaos_wf.outputs.success
    cpu_hog: !ordisabled $.steps.cpu_hog_wf.outputs.success
  workflow_error:
    error_message: !expr $.steps.error.message
    error_type: !expr $.steps.error.type
    failed_workflow: !expr $.steps.error.workflow
    retry_count: !expr $.steps.error.retry_count
