# This file is auto-generated by krkn-lib.
# It contains the rollback callable and its arguments for the scenario plugin.


# Rollback callable implementation
def rollback_callable(run_uuid: str, scenario: str, krkn_config: dict[str, any]):
    """
    Simple rollback callable that simulates a rollback operation.
    """
    print(f"Rollback called for run {run_uuid} with scenario {scenario}.")
    print(f"Krkn config: {krkn_config}")
    # Simulate a rollback operation
    # In a real scenario, this would contain logic to revert changes made during the scenario execution.
    print("Rollback operation completed successfully.")


# Setup for execution
# Create necessary variables for execution


# Execute the rollback callable
if __name__ == "__main__":
    print("Executing rollback callable...")
    rollback_callable(
        "t",
        "e",
        "s",
        "t",
        "_",
        "r",
        "u",
        "n",
        "_",
        "u",
        "u",
        "i",
        "d",
        scenario="test_scenario",
        krkn_config={"key1": "value", "key2": False, "key3": 123, "key4": ["value1", "value2", "value3"]},
    )
    print("Rollback completed.")
