apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: kraken
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
  name: kraken
---
# PersistentVolume (for Kind/Minikube/local clusters)
# On OpenShift/cloud: This will be created automatically by dynamic provisioning
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kraken-test-pv
  labels:
    type: local
spec:
  storageClassName: ""  # Empty means it can bind to any PVC with empty storageClassName
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kraken-test-pvc
  namespace: kraken
spec:
  # Empty storageClassName means:
  # - Kind/Minikube: Binds to the PV above
  # - OpenShift/Cloud: Uses default StorageClass for dynamic provisioning
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kraken-test-pod
  namespace: kraken
spec:
  securityContext:
    fsGroup: 1001
  # Smart init container that works on any platform
  initContainers:
    - name: setup-volume
      image: 'quay.io/centos7/httpd-24-centos7:centos7'
      command:
        - sh
        - -c
        - |
          set +e  # Don't exit on errors
          echo "=== Volume Setup for Kraken PVC ==="
          echo "Setting up /home/kraken..."
          
          # Create directory if it doesn't exist
          mkdir -p /home/kraken 2>/dev/null
          
          # Try to clean up old data (works on Kind/Minikube)
          echo "Attempting cleanup..."
          rm -rf /home/kraken/* 2>/dev/null
          if [ $? -eq 0 ]; then
            echo "✓ Cleaned up old data (Kind/Minikube)"
          else
            echo "○ Cleanup skipped (OpenShift/Cloud - using fresh storage)"
          fi
          
          # Try to set permissions (works on Kind/Minikube)
          chown -R 1001:1001 /home/kraken 2>/dev/null
          if [ $? -eq 0 ]; then
            echo "✓ Set ownership to 1001:1001 (Kind/Minikube)"
            chmod -R 755 /home/kraken 2>/dev/null
            echo "✓ Set permissions to 755"
          else
            echo "○ Permission setup skipped (OpenShift/Cloud - managed by StorageClass)"
          fi
          
          # Verify final state
          echo ""
          echo "=== Final Volume State ==="
          ls -la /home/kraken 2>/dev/null || echo "(Directory permissions managed by platform)"
          df -h /home/kraken 2>/dev/null || echo "(Disk usage will be available once mounted)"
          
          echo ""
          echo "✓ Volume setup complete!"
          exit 0  # Always succeed
      volumeMounts:
        - mountPath: "/home/kraken"
          name: kraken-test-pv
      securityContext:
        runAsUser: 0  # Try as root, but won't fail if not allowed
  volumes:
    - name: kraken-test-pv
      persistentVolumeClaim:
        claimName: kraken-test-pvc
  containers:
    - name: kraken-test-container
      image: 'quay.io/centos7/httpd-24-centos7:centos7'
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: "/home/kraken"
          name: kraken-test-pv
      command: ["sh", "-c", "echo 'Kraken PVC test pod ready'; while true; do sleep 30; done"]