apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: kraken
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
  name: kraken
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kraken-test-pv
  namespace: kraken
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kraken-test-pvc
  namespace: kraken
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kraken-test-pod
  namespace: kraken
spec:
  securityContext:
    fsGroup: 1001
  # initContainer to fix permissions on the mounted volume
  initContainers:
    - name: fix-permissions
      image: 'quay.io/centos7/httpd-24-centos7:centos7'
      command:
        - sh
        - -c
        - |
          echo "Setting up permissions for /home/kraken..."
          # Create the directory if it doesn't exist
          mkdir -p /home/kraken
          # Set ownership to user 1001 and group 1001
          chown -R 1001:1001 /home/kraken
          # Set permissions to allow read/write
          chmod -R 755 /home/kraken
          rm -rf /home/kraken/*
          echo "Permissions fixed. Current state:"
          ls -la /home/kraken
      volumeMounts:
        - mountPath: "/home/kraken"
          name: kraken-test-pv
      securityContext:
        runAsUser: 0  # Run as root to fix permissions
  volumes:
    - name: kraken-test-pv
      persistentVolumeClaim:
        claimName: kraken-test-pvc
  containers:
    - name: kraken-test-container
      image: 'quay.io/centos7/httpd-24-centos7:centos7'
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: "/home/kraken"
          name: kraken-test-pv
