apiVersion: v1
kind: Pod
metadata:
  name: container
  labels:
    scenario: container
spec:
  hostNetwork: true
  containers:
  - name: fedtools
    image: quay.io/fedora/fedora:latest
    command:
    - /bin/sh
    - -c
    - |
      sleep infinity