apiVersion: v1
kind: Pod
metadata:
  name: time-skew
  labels:
    scenario: time-skew
spec:
  hostNetwork: true
  containers:
  - name: fedtools
    image: quay.io/krkn-chaos/krkn:tools
    command:
    - /bin/sh
    - -c
    - |
      sleep infinity
