name: Needs Rebase

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  rebase:
    uses: krkn-chaos/actions/.github/workflows/needs-rebase.yml@d17d7433f988dc95a7ae2b15b3505b1f256dc1f6 # main
