name: Manage Stale Issues and Pull Requests

on:
  schedule:
    # Run daily at 1:00 AM UTC
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: krkn-chaos/actions/.github/workflows/stale.yml@d17d7433f988dc95a7ae2b15b3505b1f256dc1f6 # main
